myblog/comments/urls.py
from django.conf.urls import url 

from . import views

app_name = 'comments'
urlpatterns = [
    
    url(r'^comment/post/(?P<post_pk>[0-9]+)$', views.post_comment, name='post_comment'),
    
]

myblog/myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    # 评论路由
    url(r'',include('comments.urls',namespace='comments')),
    # 后台路由
    url(r'^admin/', admin.site.urls),
    # 前端路由
    url(r'^', include('myweb.urls',namespace='myweb')),
    
]

myblog/myweb/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'myweb'
urlpatterns = [

    # 博客首页
    url(r'^$', views.index, name = 'myweb_index'),
    url(r'^(?P<pIndex>[0-9]+)$', views.index, name = 'myweb_index'),
    # 文章详情页
    url(r'^post/(?P<pk>[0-9]+)$', views.detail, name = 'myweb_detail'),
    # 显示归档页面
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})$', views.archives,name = 'myweb_archives'),
    # 显示分类页面
    url(r'^category/(?P<pk>[0-9]+)$', views.category, name = 'myweb_category'),
    # 显示标签云页面
    url(r'^tag/(?P<pk>[0-9]+)$', views.tag, name = 'myweb_tag'),
    # 显示关于页面
    url(r'^about', views.about, name = 'myweb_about'),
    
    
]

myblog/comments/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    # 评论人姓名
    name = models.CharField(max_length=100)
    # 评论人邮箱
    email = models.EmailField(max_length=255)
    # 评论内容
    content = models.TextField()
    # 评论时间
    create_time = models.DateTimeField(auto_now_add=True)
    # 所评论的文章
    post = models.ForeignKey('myweb.Post',on_delete=models.CASCADE)


    def __str__(self):
        return self.content[:20]

myblog/myweb/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# 文章分类
class Category(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)

# 文章标签
class Tag(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)

# 文章主体
class Post(models.Model):
    def __str__(self):
        return self.title
    # 文章标题
    title = models.CharField(max_length=70)
    # 文章正文
    body = models.TextField()
    # 文章创建时间
    create_time = models.DateTimeField(auto_now_add=True)
    # 文章最后一次修改时间
    modified_time = models.DateTimeField(auto_now_add=True)
    # 文章摘要，允许为空
    excerpt = models.CharField(max_length=200,blank=True)
    # 文章分类
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    # 文章标签,可以为空
    tags = models.ManyToManyField(Tag,blank=True)
    # 文章作者
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    # 文章阅读量
    views = models.PositiveIntegerField(default=0)
    
    # 重定向到文章所对应的url
    def get_absolute_url(self):
        return reverse('myweb:myweb_detail',kwargs={'pk':self.pk})

    # 统计文章阅读数
    def increase_views(self):
        self.views += 1
        self.save(update_fields = ['views'])

    # 复写save方法，自动生成摘要
    def save(self,*args,**kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化MarkDown类，渲染body文本
            md = markdown.Markdown(extensions=[
                    'markdown.extensions.extra',
                    'markdown.extensions.codehilite'
                ])
            # 去掉html标签并摘取前54个字符赋给excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        # 调用父类save方法将数据保存到数据库
        super(Post,self).save(*args,**kwargs)


    # 默认按文章发布时间倒序显示
    class Meta:
        ordering = ['-create_time','title']

myblog/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','content']

    

myblog/comments/views.py
from django.shortcuts import render,get_object_or_404,redirect
from myweb.models import Post
from .models import Comment
from .forms import CommentForm

# Create your views here.


def post_comment(request,post_pk):
    # 获取被评论的文章
    post = get_object_or_404(Post,pk=post_pk)
    # 判断用户请求是否为POST请求,是则处理表单数据
    if request.method == 'POST':
        # 生成表单
        form = CommentForm(request.POST)

        # 调用 form.is_valid方法，检查表单数据是否符合要求

        if form.is_valid():

            # commit=False 作用是仅利用表单数据生成Comment实例，还不保存进数据库

            comment = form.save(commit=False)
            # 将评论与文章关联
            comment.post = post
            comment.save()
            # 重定向到文章详情页
            return redirect(post)

        else:
            # 数据不合法则重新渲染详情页
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list' : comment_list
                       }

            return render(request,'blog/detail.html',context)

    # 不是POST请求，说明用户未提交数据，重定向到文章详情页
    return redirect(post)

    

myblog/myweb/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from . models import *
import os,time
import markdown

from comments.forms import CommentForm
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q 
from django.core.paginator import Paginator 

# Create your views here.


# 前端博客首页
def index(request,pIndex=1):
    # 接收搜索条件
    q = request.GET.get('sou')
    if q:
        post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
        pIndex = int(pIndex)
        # 实例化分页类
        paginator = Paginator(post_list,6)
        # 获取分页数据对象
        list2 = paginator.page(pIndex)

        # 保存搜索条件
        wherestr = 'sou=' + q 
        # 分配数据
        context = {'post_list' : list2,'where' : wherestr}

        # 加载首页模板
        return render(request,'blog/index.html',context)
    else:
        # 获取文章
        post_list = Post.objects.all()
        pIndex = int(pIndex)
        # 实例化分页类
        paginator = Paginator(post_list,6)
        # 获取分页数据对象
        list2 = paginator.page(pIndex)
        # 分配数据
        context = {'post_list' : list2}

        # 加载首页模板
        return render(request,'blog/index.html',context)

# 文章详情页
def detail(request,pk):
    # 获取文章详情
    post = get_object_or_404(Post, pk=pk)
    # 阅读量+1
    post.increase_views()
    # 代码高亮
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    post.toc = md.toc
    form = CommentForm()
    # 获取文章全部评论
    comment_list = post.comment_set.all()
    # 分配数据
    context = {'post' : post,'form':form,'comment_list':comment_list}
    # 加载模板
    return render(request,'blog/detail.html',context)

# 显示归档页
def archives(request,year,month):
    # 获取文章
    post_list = Post.objects.filter(create_time__year=year,
                                    create_time__month=month
        )
    # 分配数据
    context = {'post_list':post_list}
    # 加载模板
    return render(request,'blog/index.html',context)

# 显示分类页
def category(request,pk):
    # 获取分类名
    cate = get_object_or_404(Category,pk=pk)
    # 获取文章并分配数据
    post_list = Post.objects.filter(category=cate)
    context = {'post_list':post_list}
    # 加载模板
    return render(request,'blog/index.html',context)

# 显示标签云页面
def tag(request,pk):
    # 获取标签名
    tag_name = get_object_or_404(Tag,pk=pk)
    # 获取文章并分配数据
    post_list = Post.objects.filter(tags=tag_name)
    context = {'post_list':post_list}
    # 加载模板
    return render(request,'blog/index.html',context)

# 显示关于页面
def about(request):
    # 返回模版
    return render(request,'blog/about.html')

myblog/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>metoo9527's blog</title>
    <link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico">
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'public/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'public/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'public/css/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'public/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'public/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'public/js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'public/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'public/js/pace.min.js' %}"></script>
    <script src="{% static 'public/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'myweb:myweb_index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'myweb:myweb_index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'myweb:myweb_index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'myweb:myweb_about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
            {% block main %}

            {% endblock %}
            
            </main>
            <aside class="col-md-3">
            {% block aside %}

            {% endblock %}
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>
<!-- 返回顶部 -->
<div class="back_top hidden-xs">
    <img src="{% static 'public/img/top.png' %}" width="8%">
</div>
<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'myweb:myweb_index' %}">首页</a></li>
            <li><a href="{% url 'myweb:myweb_index' %}">博客</a></li>
            <li><a href="{% url 'myweb:myweb_about' %}">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'public/js/script.js' %}"></script>

</body>
</html>

myblog/templates/blog/about.html
{% extends 'base.html' %}
{% block main %}
    <div class="post-content">
        <br>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;让我产生搭建一个个人博客想法的最直接启发是阅读了“Python爱好者社区”微信公众号的</p>
        <p>推送文章，作者<a target="_blank" href="https://www.zmrenwu.com/"><span class="post-link">&nbsp;追梦人物&nbsp;&nbsp;</span></a>在他的博文中详细耐心地介绍了Django的使用以及开发个人博客的流</p>
        <p>程，关于本博客的数据库架构以及前端页面，我直接使用了“追梦人物”的模版，只是做了一些微</p>
        <p>小的改动，博主强悍的技术水平，细致的教程讲解令我钦佩不已。</p>
        <br>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;同时要感谢<a target="_blank" href="http://www.itxdl.cn/"><span class="post-link">&nbsp;兄弟连IT教育&nbsp;&nbsp;</span></a>伊川老师，对于Django伊川老师是我的启蒙老师，正是这段关于</p>
        <p>Django的学习经历使我无论是在阅读“追梦人物”或者其他高人的博客还是Django的官方文档</p>
        <p>都变得轻松起来。</p>
        <br>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;本站主要内容是对自己看到的互联网知识以及自己学习过程中的总结，有些内容很可能引用</p>
        <p>了你的观点但没有注明出处，请未注明出处的朋友发邮件至我邮箱。</p>
        <br>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;联系邮箱：lu_xst9527@foxmail.com</p>
    </div>
{% endblock %}

{% block aside %}
{% load blog_tags %}
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">最新文章</h3>
        {% get_recent_posts as recent_post_list %}
        <ul>
            {% for post in recent_post_list %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% empty %}
            暂无文章!
        {% endfor %}
        </ul>
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        {% archives as date_list %}
        <ul>
            {% for date in date_list %}
            <li>
                <a href="{% url 'myweb:myweb_archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
            </li>
            {% empty %}
                暂无归档！
            {% endfor %}
        </ul>
    </div>
    <div class="widget widget-category">
        <h3 class="widget-title">分类</h3>
        {% get_categories as category_list %}
        <ul>
            {% for category in category_list %}
            <li>
                <a href="{% url 'myweb:myweb_category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
            </li>
            {% empty %}
                暂无分类！
            {% endfor %}
        </ul>
    </div>
    <div class="widget widget-tag-cloud">
        <h3 class="widget-title">标签云</h3>
        {% get_tags as tag_list %}
        <ul>
            {% for tag in tag_list %}
            <li>
                <a href="{% url 'myweb:myweb_tag' tag.pk %}">{{ tag.name }}</a>
            </li>
            {% empty %}
            暂无标签！
            {% endfor %}
        </ul>
    </div>
{% endblock %}

myblog/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
 <article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.create_time }}</time></a></span>
            <span class="comments-link"><a href="#">{{ comment_list|length }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="post-content clearfix">
        {{ post.body|safe }}
    </div>
 </article>

 <section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label }}">壮士大名：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">联系邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.content.id_for_label }}">评论：</label>
                {{ form.content }}
                {{ form.content.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ comment_list|length }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date">{{ comment.create_time }}</time>
                <div class="text">
                    {{ comment.content }}
                </div>
            </li>
            {% empty %}
            暂无评论
            {% endfor %}
        </ul>
    </div>
 </section>

{% endblock %}

{% block aside %}
{% load blog_tags %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">最新文章</h3>
        {% get_recent_posts as recent_post_list %}
        <ul>
            {% for post in recent_post_list %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% empty %}
            暂无文章!
        {% endfor %}
        </ul>
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        {% archives as date_list %}
        <ul>
            {% for date in date_list %}
            <li>
                <a href="{% url 'myweb:myweb_archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
            </li>
            {% empty %}
                暂无归档！
            {% endfor %}
        </ul>
    </div>
    <div class="widget widget-category">
        <h3 class="widget-title">分类</h3>
        {% get_categories as category_list %}
        <ul>
            {% for category in category_list %}
            <li>
                <a href="{% url 'myweb:myweb_category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
            </li>
            {% empty %}
                暂无分类！
            {% endfor %}
        </ul>
    </div>
    <div class="widget widget-tag-cloud">
        <h3 class="widget-title">标签云</h3>
        {% get_tags as tag_list %}
        <ul>
            {% for tag in tag_list %}
            <li>
                <a href="{% url 'myweb:myweb_tag' tag.pk %}">{{ tag.name }}</a>
            </li>
            {% empty %}
            暂无标签！
            {% endfor %}
        </ul>
    </div>
{% endblock %}

myblog/templates/blog/index.html
{% load static from staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>metoo9527's blog</title>
    <link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico">
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'public/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'public/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'public/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'public/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'public/js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'public/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'public/js/pace.min.js' %}"></script>
    <script src="{% static 'public/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'myweb:myweb_index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'myweb:myweb_index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'myweb:myweb_index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'myweb:myweb_about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'myweb:myweb_index' %}">
                            <input type="search" name="sou" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% for post in post_list %}
                    <article class="post post-{{ post.pk }}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="2012-11-09T23:15:57+00:00">{{ post.create_time }}</time></a></span>
                                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>{{ post.excerpt }}...</p>
                            <div class="read-more cl-effect-14">
                                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}

                <div class="am-u-lg-12 am-cf">
                    {% load pagetag %}
                    <div class="am-fr">
                        <ul class="am-pagination tpl-pagination pagination">

                            <!-- 如果有上一页则输出 -->
                            {% if post_list.has_previous %}
                            <li><a href="/{{ post_list.previous_page_number }}?{{ where }}">«</a></li>
                            {% endif %}

                            <!-- 循环页码信息 -->
                            {%  for pg in post_list.paginator.page_range %}
                            <!-- 
                            ulist.number 为当前页码  4
                            pg 为当前循环出来的页码数  1 2 3 4 5 6 7 8 9 10
                            -->
                            {% circle_page  post_list.number pg '/'  where %}

                            {% endfor %}

                            <!-- 如果有下一页则输出 -->
                            {% if post_list.has_next %}
                            <li class=""><a href="/{{ post_list.next_page_number }}?{{ where }}">»</a></li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                    {% empty %}
                        暂无文章!
                    {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'myweb:myweb_archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'myweb:myweb_category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'myweb:myweb_tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签！
                        {% endfor %}
                    </ul>
                </div>
            </aside>
        </div>
    </div>
</div>
<!-- 返回顶部 -->
<div class="back_top hidden-xs">
    <img src="{% static 'public/img/top.png' %}" width="8%">
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'myweb:myweb_index' %}">首页</a></li>
            <li><a href="{% url 'myweb:myweb_index' %}">博客</a></li>
            <li><a href="{% url 'myweb:myweb_about' %}">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'public/js/script.js' %}"></script>

</body>
</html>